name: Docker Publish

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore .env file from secrets
        run: |
          {
            echo "API_TOKEN=${{ secrets.DB_USER }}"
            echo "API_TOKEN=${{ secrets.DB_PASSWORD }}"
            echo "API_TOKEN=${{ secrets.DB_HOST }}"
            echo "API_TOKEN=${{ secrets.DB_PORT }}"
            echo "API_TOKEN=${{ secrets.DB_NAME }}"
            echo "API_TOKEN=${{ secrets.CONNECT_TIMEOUT }}"
            echo "API_TOKEN=${{ secrets.BATCH_SIZE }}"
            echo "API_TOKEN=${{ secrets.MIN_BATCH_SIZE }}"
            echo "API_TOKEN=${{ secrets.BATCH_SHRINK_FACTOR }}"
            echo "API_TOKEN=${{ secrets.BATCH_SLEEP_MS }}"
            echo "API_TOKEN=${{ secrets.BATCH_SLEEP_JITTER_MS }}"
            echo "API_TOKEN=${{ secrets.SLOWDOWN_AFTER_ROWS }}"
            echo "API_TOKEN=${{ secrets.SLOWDOWN_EXTRA_MS }}"
            echo "API_TOKEN=${{ secrets.BACKOFF_BASE_MS }}"
            echo "API_TOKEN=${{ secrets.BACKOFF_MAX_MS }}"
            echo "API_TOKEN=${{ secrets.MAX_RETRIES }}"
            echo "API_TOKEN=${{ secrets.RETRY_DELAY }}"
            echo "API_TOKEN=${{ secrets.TZ }}"
            echo "API_TOKEN=${{ secrets.CRON_TIME }}"
            echo "API_TOKEN=${{ secrets.TG_BOT_TOKEN }}"
            echo "API_TOKEN=${{ secrets.TG_CHAT_ID }}"
            echo "API_TOKEN=${{ secrets.TG_ALLOWED_USER_IDS }}"
          } > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/upeto
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}